-- 請求処理（保管料三期制・荷役料・請求書）のスキーマ（Fable設計・画面はOpusが実装）
-- 適用: tsx scripts/apply-sql.mts db/migrations/004_billing.sql
-- （db/schema.sql は新規構築用に同内容へ更新済み）

-- 履歴の対象種別に invoice / tariff を追加
ALTER TABLE edit_logs DROP CONSTRAINT edit_logs_target_type_check;
ALTER TABLE edit_logs ADD CONSTRAINT edit_logs_target_type_check
  CHECK (target_type IN ('stock','slip','slip_line','item','shipper','snapshot',
                         'warehouse','invoice','tariff'));

-- ------------------------------------------------------------
-- 11. tariffs（タリフ＝料率表）
--     荷主既定（item_id IS NULL）＋品目上書き（item_id 指定）の2段構え。
--     エンジンは品目一致 → 荷主既定 の順で解決する（判断基準の外出しの思想）。
--     単価の単位は「数量1あたり・円」。保管料は期ごと（三期制）に適用。
-- ------------------------------------------------------------
CREATE TABLE tariffs (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipper_id         INTEGER       NOT NULL REFERENCES shippers(id),
  item_id            INTEGER       NULL REFERENCES items(id),  -- NULL=荷主既定
  storage_rate       NUMERIC(12,4) NOT NULL DEFAULT 0,  -- 保管料（数量×期あたり）
  handling_in_rate   NUMERIC(12,4) NOT NULL DEFAULT 0,  -- 入庫荷役料（数量あたり）
  handling_out_rate  NUMERIC(12,4) NOT NULL DEFAULT 0,  -- 出庫荷役料（数量あたり）
  note               TEXT          NOT NULL DEFAULT '', -- 契約メモ（表示のみ・自動適用しない）
  created_at         TIMESTAMP     NOT NULL DEFAULT jst_now(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT jst_now()
);
-- item_id の NULL は UNIQUE をすり抜けるため、番兵値(0)の生成列で一意性を担保
ALTER TABLE tariffs ADD COLUMN item_key INTEGER GENERATED ALWAYS AS (COALESCE(item_id, 0)) STORED;
CREATE UNIQUE INDEX uq_tariffs ON tariffs (shipper_id, item_key);
CREATE TRIGGER trg_tariffs_updated BEFORE UPDATE ON tariffs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 12. invoices（請求書：月×荷主で1本。確定後は原本不変＝月末表と同じ流儀）
-- ------------------------------------------------------------
CREATE TABLE invoices (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_month  CHAR(7)       NOT NULL,               -- 'YYYY-MM'
  shipper_id     INTEGER       NOT NULL REFERENCES shippers(id),
  shipper_name   VARCHAR(200)  NOT NULL,               -- 確定時点のコピー（非正規化）
  total_amount   NUMERIC(14,0) NOT NULL,               -- 合計（円・円未満切り捨て済み）
  note           TEXT          NOT NULL DEFAULT '',    -- タリフ未設定品目の警告等
  finalized_by   VARCHAR(50)   NOT NULL,
  finalized_at   TIMESTAMP     NOT NULL DEFAULT jst_now(),
  CONSTRAINT uq_invoices UNIQUE (invoice_month, shipper_id)
);

-- ------------------------------------------------------------
-- 13. invoice_lines（請求明細）
--     category: storage=保管料（period_no 1..3）/ handling_in=入庫荷役 / handling_out=出庫荷役
-- ------------------------------------------------------------
CREATE TABLE invoice_lines (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id   INTEGER       NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  line_no      INTEGER       NOT NULL,
  category     TEXT          NOT NULL CHECK (category IN ('storage','handling_in','handling_out')),
  item_name    VARCHAR(200)  NOT NULL,                 -- 確定時点のコピー
  spec         VARCHAR(100)  NOT NULL DEFAULT '',
  period_no    INTEGER       NULL,                     -- 保管料のみ 1..3
  quantity     NUMERIC(14,3) NOT NULL,                 -- 課金対象数量
  unit_price   NUMERIC(12,4) NOT NULL,
  amount       NUMERIC(14,0) NOT NULL,                 -- 円未満切り捨て
  CONSTRAINT uq_invoice_lines UNIQUE (invoice_id, line_no)
);
