-- ============================================================
-- 半自動 入出庫・在庫管理ツール DBスキーマ（Postgres / Neon）
--
-- 試作（MySQL 8.x）からの移植。主な差分:
--   - ENUM → TEXT + CHECK 制約
--   - 生成列は GENERATED ALWAYS AS (...) STORED（番兵値方式は継承）
--   - updated_at の自動更新はトリガーで実現
--   - 日時は timestamp（JST壁時計）で保持し jst_now() で記録する
--   - 荷主の引き当てルールは rules/*.md を廃止し shippers テーブルが正
--   - items に商品コード・単価列を追加（単価は請求フェーズで使用）
-- ============================================================

-- JST の現在時刻（壁時計）。日時列はすべてこの値で記録する。
CREATE FUNCTION jst_now() RETURNS timestamp AS $$
  SELECT now() AT TIME ZONE 'Asia/Tokyo'
$$ LANGUAGE sql STABLE;

-- updated_at 自動更新トリガー
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := jst_now();
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- 1. warehouses（倉庫）
-- ------------------------------------------------------------
CREATE TABLE warehouses (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            VARCHAR(20)  NOT NULL,                    -- 倉庫コード
  name            VARCHAR(100) NOT NULL,
  warehouse_type  TEXT         NOT NULL DEFAULT 'normal'
                  CHECK (warehouse_type IN ('normal','chilled','frozen')),
  created_at      TIMESTAMP    NOT NULL DEFAULT jst_now(),
  updated_at      TIMESTAMP    NOT NULL DEFAULT jst_now(),
  CONSTRAINT uq_warehouses_code UNIQUE (code)
);
CREATE TRIGGER trg_warehouses_updated BEFORE UPDATE ON warehouses
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 2. shippers（荷主マスタ）
--    引き当てルール・製造日管理有無・特殊例外もこのテーブルが正
--    （試作の rules/shippers/*.md を廃止しDB化）。
--    exceptions_note は確認フォームに表示するのみで自動適用しない。
-- ------------------------------------------------------------
CREATE TABLE shippers (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                     VARCHAR(200) NOT NULL,           -- 正式名称
  name_normalized          VARCHAR(200) NOT NULL,           -- 照合用正規化名（全半角・法人格除去）
  aliases                  JSONB        NOT NULL DEFAULT '[]', -- 別名（読取名等）の配列。照合に使用
  allocation_rule          TEXT         NOT NULL DEFAULT 'fifo'
                           CHECK (allocation_rule IN ('fifo','lot_specified')),
  production_date_managed  BOOLEAN      NOT NULL DEFAULT false,
  exceptions_note          TEXT         NOT NULL DEFAULT '', -- 特殊例外（自由記述・表示のみ）
  section                  VARCHAR(100) NULL,
  phone                    VARCHAR(50)  NULL,
  fax                      VARCHAR(50)  NULL,
  email                    VARCHAR(200) NULL,
  created_at               TIMESTAMP    NOT NULL DEFAULT jst_now(),
  updated_at               TIMESTAMP    NOT NULL DEFAULT jst_now(),
  CONSTRAINT uq_shippers_normalized UNIQUE (name_normalized)
);
CREATE TRIGGER trg_shippers_updated BEFORE UPDATE ON shippers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 3. items（品目：荷主×品名×規格 で一意）
--    item_code / unit_price は商品マスタ管理画面で保守（単価は請求フェーズで使用）。
-- ------------------------------------------------------------
CREATE TABLE items (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipper_id       INTEGER      NOT NULL REFERENCES shippers(id),
  name             VARCHAR(200) NOT NULL,                   -- 品名
  spec             VARCHAR(100) NOT NULL DEFAULT '',        -- 規格（g等）。無い場合は空文字
  name_normalized  VARCHAR(200) NOT NULL,                   -- 表記ゆれ照合用（1.8=1.80 の寄せに使用）
  item_code        VARCHAR(50)  NOT NULL DEFAULT '',        -- 商品コード
  unit_price       NUMERIC(12,2) NULL,                      -- 単価（請求フェーズで使用。未設定可）
  status           TEXT         NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active','hold')),     -- hold=似た品名で担当確認待ち
  created_at       TIMESTAMP    NOT NULL DEFAULT jst_now(),
  updated_at       TIMESTAMP    NOT NULL DEFAULT jst_now(),
  CONSTRAINT uq_items UNIQUE (shipper_id, name, spec)
);
CREATE INDEX idx_items_normalized ON items (shipper_id, name_normalized);
CREATE TRIGGER trg_items_updated BEFORE UPDATE ON items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 4. stock（在庫）
--    一意キー：倉庫 × 品目(=荷主×品名×規格) × 製造日 × ロット × 特定番号
--    製造日管理なし荷主は production_date=NULL。
--    NULLはUNIQUEをすり抜けるため、番兵値('1000-01-01')の生成列で一意性を担保。
-- ------------------------------------------------------------
CREATE TABLE stock (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id         INTEGER       NOT NULL REFERENCES warehouses(id),
  item_id              INTEGER       NOT NULL REFERENCES items(id),
  production_date      DATE          NULL,                  -- 製造日（管理なしはNULL）
  production_date_key  DATE          GENERATED ALWAYS AS
                       (COALESCE(production_date, DATE '1000-01-01')) STORED,
  lot_no               VARCHAR(50)   NOT NULL DEFAULT '',   -- ロット番号
  order_no             VARCHAR(100)  NOT NULL DEFAULT '',   -- 特定番号（オーダー番号）
  quantity             NUMERIC(12,3) NOT NULL DEFAULT 0,
  version              INTEGER       NOT NULL DEFAULT 0,    -- 楽観的ロック（行単位）
  created_at           TIMESTAMP     NOT NULL DEFAULT jst_now(),
  updated_at           TIMESTAMP     NOT NULL DEFAULT jst_now(),
  CONSTRAINT uq_stock UNIQUE (warehouse_id, item_id, production_date_key, lot_no, order_no)
);
CREATE INDEX idx_stock_item ON stock (item_id, production_date);  -- FIFO引き当て用
CREATE TRIGGER trg_stock_updated BEFORE UPDATE ON stock
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 5. slips（伝票：取り込んだ依頼1件=1行）
-- ------------------------------------------------------------
CREATE TABLE slips (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slip_type      TEXT         NOT NULL CHECK (slip_type IN ('inbound','outbound')),
  source_type    TEXT         NOT NULL CHECK (source_type IN ('fax','mail')),
  slip_number    VARCHAR(100) NOT NULL DEFAULT '',          -- 伝票番号（読取値）
  fingerprint    CHAR(64)     NOT NULL,                     -- 指紋 = SHA-256(伝票番号+正規化明細)
  status         TEXT         NOT NULL DEFAULT 'unprocessed'
                 CHECK (status IN ('unprocessed','confirmed','done','hold')),
  shipper_id     INTEGER      NULL REFERENCES shippers(id), -- 照合後に紐付け（未確定はNULL）
  requested_at   TIMESTAMP    NULL,                         -- 依頼日時（伝票上の日付）
  movement_date  DATE         NULL,                         -- 入出庫日（書類上の出荷日/入荷日。サマリーの基準日）
  received_at    TIMESTAMP    NOT NULL,                     -- 取込日時
  source_file    VARCHAR(500) NULL,                         -- 元PDF（Vercel Blob URL 等）
  extracted_json JSONB        NULL,                         -- Claude読取の生結果（監査用に保持）
  confidence     TEXT         NULL CHECK (confidence IN ('high','medium','low')),
  note           TEXT         NULL,                         -- 読めない箇所・気になる点メモ
  hold_reason    TEXT         NULL,                         -- 保留理由
  assigned_to    VARCHAR(50)  NULL,                         -- 担当者コード（operators.code）
  confirmed_by   VARCHAR(50)  NULL,                         -- 確定者（担当者コード）
  confirmed_at   TIMESTAMP    NULL,
  version        INTEGER      NOT NULL DEFAULT 0,           -- 楽観的ロック
  editing_by     VARCHAR(50)  NULL,                         -- 「編集中」表示用
  editing_at     TIMESTAMP    NULL,
  created_at     TIMESTAMP    NOT NULL DEFAULT jst_now(),
  updated_at     TIMESTAMP    NOT NULL DEFAULT jst_now(),
  CONSTRAINT uq_slips_fingerprint UNIQUE (fingerprint)      -- 二重読込防止
);
CREATE INDEX idx_slips_status ON slips (status, received_at);
CREATE INDEX idx_slips_assigned ON slips (assigned_to, status);  -- 担当者の案件フィルタ用
CREATE TRIGGER trg_slips_updated BEFORE UPDATE ON slips
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 6. slip_lines（伝票明細）
--    1枚の依頼書に複数品目が載るのが常のため、明細を別テーブルに分離。
-- ------------------------------------------------------------
CREATE TABLE slip_lines (
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slip_id                 INTEGER       NOT NULL REFERENCES slips(id) ON DELETE CASCADE,
  line_no                 INTEGER       NOT NULL,            -- 伝票内の行番号
  item_name_raw           VARCHAR(200)  NOT NULL,            -- 読取そのままの品名（監査用）
  spec_raw                VARCHAR(100)  NOT NULL DEFAULT '',
  item_code_raw           VARCHAR(50)   NOT NULL DEFAULT '', -- 読取そのままの商品コード（照合ヒント）
  item_id                 INTEGER       NULL REFERENCES items(id),
  warehouse_id            INTEGER       NULL REFERENCES warehouses(id),
  production_date         DATE          NULL,
  lot_no                  VARCHAR(50)   NOT NULL DEFAULT '',
  order_no                VARCHAR(100)  NOT NULL DEFAULT '', -- 特定番号（オーダー番号）
  quantity                NUMERIC(12,3) NOT NULL,            -- 依頼数量（入庫票の値）
  site_reported_quantity  NUMERIC(12,3) NULL,                -- 現場報告値（突合用。食い違いは確認へ）
  line_status             TEXT          NOT NULL DEFAULT 'ok'
                          CHECK (line_status IN ('ok','hold')),
  hold_reason             TEXT          NULL,                -- 似た品名・ロット不明 等
  CONSTRAINT uq_slip_lines UNIQUE (slip_id, line_no)
);

-- ------------------------------------------------------------
-- 7. stock_snapshots（月末スナップショット：確定＝翌月期首）
--    確定時点の名称・規格を非正規化コピーで保持（後からマスタが変わっても月末表は不変）。
-- ------------------------------------------------------------
CREATE TABLE stock_snapshots (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_month       CHAR(7)       NOT NULL,               -- 'YYYY-MM'
  warehouse_id         INTEGER       NOT NULL,
  item_id              INTEGER       NOT NULL,
  production_date      DATE          NULL,
  production_date_key  DATE          GENERATED ALWAYS AS
                       (COALESCE(production_date, DATE '1000-01-01')) STORED,
  lot_no               VARCHAR(50)   NOT NULL DEFAULT '',
  order_no             VARCHAR(100)  NOT NULL DEFAULT '',
  quantity             NUMERIC(12,3) NOT NULL,
  shipper_name         VARCHAR(200)  NOT NULL,               -- 確定時点のコピー
  item_name            VARCHAR(200)  NOT NULL,               -- 〃
  spec                 VARCHAR(100)  NOT NULL DEFAULT '',    -- 〃
  warehouse_code       VARCHAR(20)   NOT NULL,               -- 〃
  finalized_by         VARCHAR(50)   NOT NULL,               -- 確定者
  finalized_at         TIMESTAMP     NOT NULL,
  CONSTRAINT uq_snapshots UNIQUE (snapshot_month, warehouse_id, item_id,
                                  production_date_key, lot_no, order_no)
);
CREATE INDEX idx_snapshots_month ON stock_snapshots (snapshot_month);

-- ------------------------------------------------------------
-- 8. edit_logs（修正履歴：いつ・誰が・何を・なぜ）
--    確定/保留/手修正/月末確定 すべての状態変更をここに残す。
-- ------------------------------------------------------------
CREATE TABLE edit_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type  TEXT        NOT NULL
               CHECK (target_type IN ('stock','slip','slip_line','item','shipper','snapshot',
                                      'warehouse','invoice','tariff')),
  target_id    INTEGER     NOT NULL,
  action       TEXT        NOT NULL
               CHECK (action IN ('create','update','confirm','hold','release','adjust','finalize')),
  field        VARCHAR(100) NULL,                            -- 変更フィールド名
  old_value    TEXT        NULL,
  new_value    TEXT        NULL,
  reason       TEXT        NOT NULL,                         -- なぜ（手修正ではUI必須入力）
  operator     VARCHAR(50) NOT NULL,                         -- 誰が（担当者コード）
  created_at   TIMESTAMP   NOT NULL DEFAULT jst_now()        -- いつ
);
CREATE INDEX idx_logs_target ON edit_logs (target_type, target_id);
CREATE INDEX idx_logs_created ON edit_logs (created_at);

-- ------------------------------------------------------------
-- 8.5 snapshot_overrides（月末表の表示値修正：現場要件による追加）
--     スナップショット本体は不変のまま、指定行の「表示数量」だけを
--     差し替えるレイヤー。同一行に複数回の修正が入った場合は最新(idが最大)が有効。
-- ------------------------------------------------------------
CREATE TABLE snapshot_overrides (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id        INTEGER       NOT NULL REFERENCES stock_snapshots(id),
  override_quantity  NUMERIC(12,3) NOT NULL,                 -- 差し替え後の表示数量
  reason             TEXT          NOT NULL,                 -- なぜ（必須。例：メーカー帳簿突合）
  operator           VARCHAR(50)   NOT NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT jst_now()
);
CREATE INDEX idx_overrides_snapshot ON snapshot_overrides (snapshot_id, id);

-- ------------------------------------------------------------
-- 9. operators（担当者マスタ）
--    最小権限「担当者コードによる案件フィルタ」の正となるマスタ。
--    confirmed_by / operator / finalized_by 等の VARCHAR(50) は
--    このテーブルの code を入れる運用。認証（Clerk）のユーザーと
--    clerk_user_id で紐付ける（履歴表示の可読性のため code を維持）。
-- ------------------------------------------------------------
CREATE TABLE operators (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           VARCHAR(50)  NOT NULL,                      -- 担当者コード
  name           VARCHAR(100) NOT NULL,
  email          VARCHAR(200) NULL,                          -- 通知先（任意）
  clerk_user_id  VARCHAR(100) NULL,                          -- Clerk ユーザーID（認証との紐付け）
  is_active      BOOLEAN      NOT NULL DEFAULT true,         -- 退職・異動は削除せず無効化
  created_at     TIMESTAMP    NOT NULL DEFAULT jst_now(),
  updated_at     TIMESTAMP    NOT NULL DEFAULT jst_now(),
  CONSTRAINT uq_operators_code UNIQUE (code)
);
CREATE TRIGGER trg_operators_updated BEFORE UPDATE ON operators
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 10. intake_logs（取込ログ）
--     「黙って捨てない」の証跡。無関係メール・重複・エラーは
--     伝票（slips）にならないため、取込の全件をここに記録する。
-- ------------------------------------------------------------
CREATE TABLE intake_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type  TEXT         NOT NULL CHECK (source_type IN ('fax','mail')),
  source_ref   VARCHAR(500) NOT NULL,                        -- PDF名/Blob URL or メールMessage-ID
  result       TEXT         NOT NULL
               CHECK (result IN ('slip_created',  -- 伝票を起こした
                                 'irrelevant',    -- 入出庫と無関係（通知対象）
                                 'duplicate',     -- 指紋一致で二重読込を弾いた
                                 'error')),       -- 読取失敗等（通知対象）
  slip_id      INTEGER      NULL REFERENCES slips(id),       -- 起こした伝票（result=slip_created時）
  note         TEXT         NULL,                            -- 判定理由・エラー内容
  notified_at  TIMESTAMP    NULL,                            -- Slack通知した日時（未通知はNULL）
  created_at   TIMESTAMP    NOT NULL DEFAULT jst_now()
);
CREATE INDEX idx_intake_result ON intake_logs (result, created_at);

-- ------------------------------------------------------------
-- 11. tariffs（タリフ＝料率表：請求処理）
--     荷主既定（item_id IS NULL）＋品目上書き（item_id 指定）の2段構え。
--     エンジンは品目一致 → 荷主既定 の順で解決する（判断基準の外出しの思想）。
--     単価の単位は「数量1あたり・円」。保管料は期ごと（三期制）に適用。
-- ------------------------------------------------------------
CREATE TABLE tariffs (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipper_id         INTEGER       NOT NULL REFERENCES shippers(id),
  item_id            INTEGER       NULL REFERENCES items(id),  -- NULL=荷主既定
  storage_rate       NUMERIC(12,4) NOT NULL DEFAULT 0,  -- 保管料（数量×期あたり）
  handling_in_rate   NUMERIC(12,4) NOT NULL DEFAULT 0,  -- 入庫荷役料（数量あたり）
  handling_out_rate  NUMERIC(12,4) NOT NULL DEFAULT 0,  -- 出庫荷役料（数量あたり）
  note               TEXT          NOT NULL DEFAULT '', -- 契約メモ（表示のみ・自動適用しない）
  item_key           INTEGER       GENERATED ALWAYS AS (COALESCE(item_id, 0)) STORED,
  created_at         TIMESTAMP     NOT NULL DEFAULT jst_now(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT jst_now()
);
CREATE UNIQUE INDEX uq_tariffs ON tariffs (shipper_id, item_key);
CREATE TRIGGER trg_tariffs_updated BEFORE UPDATE ON tariffs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 12. invoices（請求書：月×荷主で1本。確定後は原本不変＝月末表と同じ流儀）
-- ------------------------------------------------------------
--     status: draft=確認中（調整・例外行の追加が可能）/ issued=発行済（不変・印刷可）
CREATE TABLE invoices (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_month  CHAR(7)       NOT NULL,               -- 'YYYY-MM'
  shipper_id     INTEGER       NOT NULL REFERENCES shippers(id),
  shipper_name   VARCHAR(200)  NOT NULL,               -- 確定時点のコピー（非正規化）
  total_amount   NUMERIC(14,0) NOT NULL,               -- 合計（表示値の合算・円未満切り捨て済み）
  note           TEXT          NOT NULL DEFAULT '',    -- タリフ未設定品目の警告等
  status         TEXT          NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft','issued')),
  finalized_by   VARCHAR(50)   NOT NULL,               -- 締め（下書き作成）担当
  finalized_at   TIMESTAMP     NOT NULL DEFAULT jst_now(),
  issued_by      VARCHAR(50)   NULL,                   -- 発行担当
  issued_at      TIMESTAMP     NULL,
  CONSTRAINT uq_invoices UNIQUE (invoice_month, shipper_id)
);

-- ------------------------------------------------------------
-- 13. invoice_lines（請求明細）
--     category: storage=保管料（period_no 1..3）/ handling_in=入庫荷役 / handling_out=出庫荷役
--             / manual=例外請求行（確認フォームで手動追加）
--     amount=原本（計算値・不変）、adjusted_amount=表示調整（月末表の表示値修正と同思想）
-- ------------------------------------------------------------
CREATE TABLE invoice_lines (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id      INTEGER       NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  line_no         INTEGER       NOT NULL,
  category        TEXT          NOT NULL CHECK (category IN ('storage','handling_in','handling_out','manual')),
  item_name       VARCHAR(200)  NOT NULL,                 -- 確定時点のコピー
  spec            VARCHAR(100)  NOT NULL DEFAULT '',
  period_no       INTEGER       NULL,                     -- 保管料のみ 1..3
  quantity        NUMERIC(14,3) NOT NULL,                 -- 課金対象数量
  unit_price      NUMERIC(12,4) NOT NULL,
  amount          NUMERIC(14,0) NOT NULL,                 -- 原本（円未満切り捨て）
  adjusted_amount NUMERIC(14,0) NULL,                     -- 表示調整（NULL=無調整）
  adjust_reason   TEXT          NULL,
  CONSTRAINT uq_invoice_lines UNIQUE (invoice_id, line_no)
);
